name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '26'
  ABBOS_COVERAGE_FILE_PATH: './coverage/abbos/clover.xml'
  PLAYGROUND_COVERAGE_FILE_PATH: './coverage/playground/clover.xml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Application Dependencies
        run: npm ci

      - name: Check Formatting
        run: npx prettier --check .

      - name: Build Abbos Library
        run: npx ng build abbos

      - name: Test Abbos Library
        run: npx ng test abbos --coverage --watch=false

      - name: Post Abbos Code Coverage Comments
        if: github.event_name == 'pull_request'
        uses: kcjpop/coverage-comments@v2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: ${{ env.ABBOS_COVERAGE_FILE_PATH }}

      - name: Build Playground
        run: npx ng build playground

      - name: Test Playground
        run: npx ng test playground --coverage --watch=false

      - name: Post Playground Code Coverage Comments
        if: github.event_name == 'pull_request'
        uses: kcjpop/coverage-comments@v2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: ${{ env.PLAYGROUND_COVERAGE_FILE_PATH }}
